language: python
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

# Create database for test
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate --settings=core.settings

# command to run tests
script:
  - coverage run --source=app manage.py test --settings=core.settings
  - flake 8 .

after_success:
  coveralls

notifications:
  slack: teamtaverna:iP55LweubU8UOBgu9e0cTeED
